// <auto-generated />
namespace AuthorizationServer.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddImage02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImage02));
        
        string IMigrationMetadata.Id
        {
            get { return "201805271625007_AddImage02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
